repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-toml

      - id: check-yaml

      - id: trailing-whitespace
        types: [non-executable, file, text]
        exclude_types: [markdown]

      - id: end-of-file-fixer
        types: [non-executable, file, text]
        exclude_types: [markdown]

  - repo: local
    hooks:
      - id: rustfmt
        name: cargo fmt
        entry: cargo fmt
        pass_filenames: false
        language: system
        types: [rust]

      - id: clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        pass_filenames: false
        language: system
        types: [rust]

      - id: test
        name: cargo test
        entry: cargo test
        pass_filenames: false
        language: system
        types: [rust]
        stages: [push]
